//! Executable NYC taxi tutorial for `diesel-clickhouse`.
//!
//! The example runs the same broad workflow as the ClickHouse tutorial and emits
//! the project's tutorial Markdown. The prose lives here intentionally: running
//! the example makes `docs/TUTORIAL.md` a real document backed by live queries.
//!
//! ```text
//! CLICKHOUSE_URL=http://default:password@localhost:8123/default \
//!   cargo run --example tutorial -- --write docs/TUTORIAL.md
//! ```
//!
//! The run downloads the public NYC taxi data from S3 into a `trips` table.

use std::env;
use std::error::Error;
use std::fs;

use diesel::connection::SimpleConnection;
use diesel::dsl::{count_star, sql};
use diesel::expression::SqlLiteral;
use diesel::prelude::*;
use diesel::sql_types::{BigInt, Bool, Float, Text};
use diesel_clickhouse::{ClickHouseConnectionOptions, DataType, create_table, merge_tree, to_sql};

type Result<T> = std::result::Result<T, Box<dyn Error + Send + Sync>>;

diesel::table! {
    use diesel::sql_types::*;
    use diesel_clickhouse::sql_types::*;

    // Diesel schemas may declare only the columns a Rust query needs. The DDL
    // below creates the full ClickHouse tutorial table; this compact schema
    // keeps the example below Diesel's default 32-column compile-time limit.
    trips (trip_id) {
        trip_id -> UInt32,
        pickup_date -> Date,
        passenger_count -> UInt8,
        tip_amount -> Float,
        total_amount -> Float,
        pickup_ntaname -> Text,
        dropoff_nyct2010_gid -> UInt8,
    }
}

diesel::table! {
    use diesel::sql_types::*;
    use diesel_clickhouse::sql_types::*;

    #[sql_name = "taxi_zone_dictionary"]
    taxi_zone_dictionary (location_id) {
        #[sql_name = "LocationID"]
        location_id -> UInt16,
        #[sql_name = "Borough"]
        borough -> Text,
        #[sql_name = "Zone"]
        zone -> Text,
        service_zone -> Text,
    }
}

#[derive(Debug, QueryableByName)]
struct BoroughTotal {
    #[diesel(sql_type = BigInt)]
    total: i64,
    #[diesel(sql_type = Text)]
    borough: String,
}

fn main() -> Result<()> {
    let mut output = None;
    let mut args = env::args().skip(1);
    while let Some(arg) = args.next() {
        if arg == "--write" {
            output = args.next();
        }
    }

    let database_url = env::var("CLICKHOUSE_URL")
        .unwrap_or_else(|_| "http://default:password@localhost:8123/default".to_owned());
    let mut conn = ClickHouseConnectionOptions::from_url(&database_url)?.connect()?;
    let mut doc = TutorialDoc::new();

    doc.heading(1, "NYC taxi tutorial with Diesel and ClickHouse");
    doc.paragraph("This tutorial mirrors the [ClickHouse NYC taxi tutorial](https://clickhouse.com/docs/tutorial), but shows the Diesel code next to the ClickHouse SQL. It uses the HTTP-backed `ClickHouseConnection` provided by this crate.");
    doc.paragraph("This file is generated by `examples/tutorial.rs`. To update it, run the tutorial against a live ClickHouse server; the Markdown prose, SQL snippets, Rust snippets, and observed output blocks are emitted together from that example.");

    doc.heading(2, "Regenerate this document");
    doc.paragraph("The easiest path is the `just` recipe. It starts a disposable ClickHouse container, runs the tutorial example, writes this file, and removes the container when the run finishes.");
    doc.code("bash", "just tutorial");
    doc.paragraph("Under the hood, the recipe starts ClickHouse with the equivalent of this Docker command. It maps the HTTP port to a random localhost port so it does not collide with an existing ClickHouse server:");
    doc.code("bash", DOCKER_RUN_BASH);
    doc.paragraph("After ClickHouse is ready, the recipe discovers the mapped port and points the example at that fresh server:");
    doc.code("bash", RUN_TUTORIAL_BASH);
    doc.paragraph("The example downloads the public NYC taxi data from S3 when the `trips` table is empty. The `text` output blocks below are from the live run that generated this document, so small value or ordering differences can appear if the upstream dataset or ClickHouse version changes.");

    doc.heading(2, "Connect");
    doc.paragraph("ClickHouse SQL clients connect to the server directly. In Diesel, create a `ClickHouseConnection` from a URL or explicit options:");
    doc.rust(CONNECT_RUST);
    doc.paragraph("`ClickHouseConnection::establish(\"http://user:password@host:8123/database\")` is equivalent for URL-first configuration. The executable tutorial reads `CLICKHOUSE_URL` and uses `ClickHouseConnectionOptions::from_url(...)` so it can run against the disposable container created by `just tutorial` or against your own ClickHouse server.");
    doc.output("connection established");

    doc.heading(2, "Declare the Diesel schema");
    doc.paragraph("Diesel's `table!` schema can declare just the columns your Rust queries use. The ClickHouse table created below has more columns than this compact schema; the example keeps only the columns used in the tutorial queries.");
    doc.rust(SCHEMA_RUST);
    doc.paragraph("Use `diesel::dsl::sql::<ST>(...)` for tutorial expressions that are ClickHouse-specific but still have a known result type.");

    doc.heading(2, "Create the `trips` table");
    doc.paragraph("ClickHouse SQL from the tutorial, rendered by this crate's DDL builder:");
    let create_trips_sql = create_trips_sql()?;
    doc.sql(&create_trips_sql);
    doc.paragraph("The same table is built with this crate's DDL builder. `DataType::custom(...)` is the escape hatch for ClickHouse type expressions that do not need a dedicated Rust enum variant, such as `FixedString(25)`.");
    doc.rust(CREATE_TRIPS_RUST);
    diesel::sql_query(&create_trips_sql).execute(&mut conn)?;
    doc.output("created `trips` if it did not already exist");

    doc.heading(2, "Add the dataset");
    doc.paragraph(
        "The tutorial loads the public dataset from S3 with ClickHouse's `s3(...)` table function:",
    );
    doc.sql(INSERT_TRIPS_SQL.trim());
    doc.paragraph("This is a good place to use raw SQL with `batch_execute`, because ingestion from a ClickHouse table function is already ClickHouse-specific. The executable tutorial only performs the insert when the table is empty, which makes reruns safe against a reused database.");
    doc.rust(INSERT_TRIPS_RUST);
    let existing: i64 = trips::table.select(count_star()).first(&mut conn)?;
    if existing == 0 {
        conn.batch_execute(INSERT_TRIPS_SQL)?;
    }
    let row_count: i64 = trips::table.select(count_star()).first(&mut conn)?;
    doc.output(&format!("trips rows: {row_count}"));

    doc.heading(2, "Analyze the data");

    doc.heading(3, "Average tip amount");
    doc.sql("SELECT round(avg(tip_amount), 2) FROM trips");
    doc.paragraph("Diesel version:");
    doc.rust(AVG_TIP_RUST);
    let avg_tip: f32 = trips::table
        .select(sql::<Float>("round(avg(`tip_amount`), 2)"))
        .first(&mut conn)?;
    doc.output(&format!("average tip: {avg_tip:.2}"));

    doc.heading(3, "Average cost by passenger count");
    doc.sql(
        "SELECT\n    passenger_count,\n    ceil(avg(total_amount), 2) AS average_total_amount\nFROM trips\nGROUP BY passenger_count",
    );
    doc.paragraph("Diesel version:");
    doc.rust(BY_PASSENGER_RUST);
    let by_passenger: Vec<(u8, f32)> = trips::table
        .select((
            trips::passenger_count,
            sql::<Float>("ceil(avg(`total_amount`), 2)"),
        ))
        .group_by(trips::passenger_count)
        .order(trips::passenger_count.asc())
        .load(&mut conn)?;
    doc.output(&format_rows(&by_passenger));

    doc.heading(3, "Daily pickups per neighborhood");
    doc.sql(
        "SELECT\n    pickup_date,\n    pickup_ntaname,\n    SUM(1) AS number_of_trips\nFROM trips\nGROUP BY pickup_date, pickup_ntaname\nORDER BY pickup_date ASC, pickup_ntaname ASC\nLIMIT 10",
    );
    doc.paragraph("Diesel version:");
    doc.rust(DAILY_PICKUPS_RUST);
    let daily_pickups: Vec<(String, String, i64)> = trips::table
        .group_by((trips::pickup_date, trips::pickup_ntaname))
        .select((trips::pickup_date, trips::pickup_ntaname, count_star()))
        .order((trips::pickup_date.asc(), trips::pickup_ntaname.asc()))
        .limit(10)
        .load(&mut conn)?;
    doc.output(&format_rows(&daily_pickups));
    doc.paragraph("`Date` currently loads as a string through the HTTP text row decoder, hence `String` for `pickup_date`.");

    doc.heading(2, "Create and query a dictionary");
    doc.paragraph("The ClickHouse tutorial creates a dictionary from a public CSV:");
    doc.sql(CREATE_DICTIONARY_SQL.trim());
    doc.paragraph("Use `batch_execute` for dictionary DDL. The executable tutorial drops and recreates the dictionary first so repeated runs observe the same definition.");
    doc.rust("conn.batch_execute(\"DROP DICTIONARY IF EXISTS taxi_zone_dictionary\")?;\nconn.batch_execute(CREATE_DICTIONARY_SQL)?;");
    conn.batch_execute("DROP DICTIONARY IF EXISTS taxi_zone_dictionary")?;
    conn.batch_execute(CREATE_DICTIONARY_SQL)?;
    doc.output("created `taxi_zone_dictionary`");

    doc.paragraph("Query dictionary functions with typed SQL fragments:");
    doc.sql("SELECT dictGet('taxi_zone_dictionary', 'Borough', 132);\nSELECT dictHas('taxi_zone_dictionary', 132);");
    doc.rust(DICTIONARY_LOOKUP_RUST);
    let borough: String = diesel::select(sql::<Text>(
        "dictGet('taxi_zone_dictionary', 'Borough', 132)",
    ))
    .get_result(&mut conn)?;
    doc.output(&borough);
    let has_jfk: bool = diesel::select(sql::<Bool>("dictHas('taxi_zone_dictionary', 132)"))
        .get_result(&mut conn)?;
    doc.output(&format!("dict has 132: {has_jfk}"));

    doc.paragraph("Use dictionary lookups inside a Diesel query by wrapping the ClickHouse expression in `sql::<Text>(...)` and grouping by the same expression:");
    doc.sql(
        "SELECT\n    count(1) AS total,\n    dictGetOrDefault(\n        'taxi_zone_dictionary',\n        'Borough',\n        toUInt64(pickup_nyct2010_gid),\n        'Unknown'\n    ) AS borough_name\nFROM trips\nWHERE dropoff_nyct2010_gid = 132 OR dropoff_nyct2010_gid = 138\nGROUP BY borough_name\nORDER BY total DESC",
    );
    doc.rust(BOROUGH_PICKUPS_RUST);
    let borough_pickups: Vec<(i64, String)> = trips::table
        .filter(sql::<Bool>(
            "dropoff_nyct2010_gid = 132 OR dropoff_nyct2010_gid = 138",
        ))
        .group_by(pickup_borough_expr())
        .select((count_star(), pickup_borough_expr()))
        .order(count_star().desc())
        .load(&mut conn)?;
    doc.output(&format_rows(&borough_pickups));

    doc.heading(2, "Perform a join");
    doc.paragraph("ClickHouse can also join the dictionary with the `trips` table:");
    doc.sql(JOIN_SQL.trim());
    doc.paragraph("Diesel's built-in ANSI join source is not always the shape ClickHouse expects for executable joins, and ClickHouse dictionaries are a particularly SQL-native feature. For this part of the tutorial, use `sql_query` plus `QueryableByName`:");
    doc.rust(JOIN_RUST);
    let joined: Vec<BoroughTotal> = diesel::sql_query(JOIN_SQL).load(&mut conn)?;
    let joined_rows = joined
        .iter()
        .map(|row| (row.total, row.borough.clone()))
        .collect::<Vec<_>>();
    doc.output(&format_rows(&joined_rows));

    doc.heading(2, "What this tutorial demonstrates");
    doc.unordered_list(&[
        "Use Diesel schemas for ClickHouse tables, including declaring only the columns a Rust query needs.",
        "Build ClickHouse DDL with `create_table`, `DataType`, and `merge_tree`.",
        "Use `ClickHouseConnection` for ordinary `.load`, `.first`, `.execute`, and `.batch_execute` calls.",
        "Mix Diesel's typed query builder with `sql::<ST>(...)` for ClickHouse-specific expressions.",
        "Use `sql_query` / `QueryableByName` when a ClickHouse feature is more naturally represented as SQL than a Diesel AST.",
    ]);

    let markdown = doc.finish();
    if let Some(path) = output {
        fs::write(&path, markdown)?;
        eprintln!("wrote {path}");
    } else {
        print!("{markdown}");
    }

    Ok(())
}

fn pickup_borough_expr() -> SqlLiteral<Text> {
    sql::<Text>(
        "dictGetOrDefault('taxi_zone_dictionary','Borough', toUInt64(`pickup_nyct2010_gid`), 'Unknown')",
    )
}

fn create_trips_sql() -> Result<String> {
    let ddl = create_table("trips")
        .if_not_exists()
        .column("trip_id", DataType::UInt32)
        .column("vendor_id", taxi_vendor_type())
        .column("pickup_date", DataType::Date)
        .column("pickup_datetime", DataType::DateTime)
        .column("dropoff_date", DataType::Date)
        .column("dropoff_datetime", DataType::DateTime)
        .column("store_and_fwd_flag", DataType::UInt8)
        .column("rate_code_id", DataType::UInt8)
        .column("pickup_longitude", DataType::Float64)
        .column("pickup_latitude", DataType::Float64)
        .column("dropoff_longitude", DataType::Float64)
        .column("dropoff_latitude", DataType::Float64)
        .column("passenger_count", DataType::UInt8)
        .column("trip_distance", DataType::Float64)
        .column("fare_amount", DataType::Float32)
        .column("extra", DataType::Float32)
        .column("mta_tax", DataType::Float32)
        .column("tip_amount", DataType::Float32)
        .column("tolls_amount", DataType::Float32)
        .column("ehail_fee", DataType::Float32)
        .column("improvement_surcharge", DataType::Float32)
        .column("total_amount", DataType::Float32)
        .column("payment_type", payment_type())
        .column("trip_type", DataType::UInt8)
        .column("pickup", DataType::custom("FixedString(25)"))
        .column("dropoff", DataType::custom("FixedString(25)"))
        .column("cab_type", cab_type())
        .column("pickup_nyct2010_gid", DataType::Int8)
        .column("pickup_ctlabel", DataType::Float32)
        .column("pickup_borocode", DataType::Int8)
        .column("pickup_ct2010", DataType::String)
        .column("pickup_boroct2010", DataType::String)
        .column("pickup_cdeligibil", DataType::String)
        .column("pickup_ntacode", DataType::custom("FixedString(4)"))
        .column("pickup_ntaname", DataType::String)
        .column("pickup_puma", DataType::UInt16)
        .column("dropoff_nyct2010_gid", DataType::UInt8)
        .column("dropoff_ctlabel", DataType::Float32)
        .column("dropoff_borocode", DataType::UInt8)
        .column("dropoff_ct2010", DataType::String)
        .column("dropoff_boroct2010", DataType::String)
        .column("dropoff_cdeligibil", DataType::String)
        .column("dropoff_ntacode", DataType::custom("FixedString(4)"))
        .column("dropoff_ntaname", DataType::String)
        .column("dropoff_puma", DataType::UInt16)
        .engine(
            merge_tree()
                .partition_by(["toYYYYMM(pickup_date)"])
                .order_by(["pickup_datetime"]),
        );
    Ok(to_sql(&ddl)?)
}

fn taxi_vendor_type() -> DataType {
    DataType::enum8([
        ("1", 1),
        ("2", 2),
        ("3", 3),
        ("4", 4),
        ("CMT", 5),
        ("VTS", 6),
        ("DDS", 7),
        ("B02512", 10),
        ("B02598", 11),
        ("B02617", 12),
        ("B02682", 13),
        ("B02764", 14),
        ("", 15),
    ])
}

fn payment_type() -> DataType {
    DataType::enum8([("UNK", 0), ("CSH", 1), ("CRE", 2), ("NOC", 3), ("DIS", 4)])
}

fn cab_type() -> DataType {
    DataType::enum8([("yellow", 1), ("green", 2), ("uber", 3)])
}

fn format_rows<T: std::fmt::Debug>(rows: &[T]) -> String {
    format!("{rows:#?}")
}

struct TutorialDoc {
    markdown: String,
}

impl TutorialDoc {
    fn new() -> Self {
        Self {
            markdown: String::new(),
        }
    }

    fn heading(&mut self, level: usize, title: &str) {
        self.markdown
            .push_str(&format!("\n{} {title}\n\n", "#".repeat(level)));
    }

    fn paragraph(&mut self, text: &str) {
        self.markdown.push_str(text);
        self.markdown.push_str("\n\n");
    }

    fn unordered_list(&mut self, items: &[&str]) {
        for item in items {
            self.markdown.push_str("- ");
            self.markdown.push_str(item);
            self.markdown.push('\n');
        }
        self.markdown.push('\n');
    }

    fn sql(&mut self, sql: &str) {
        self.code("sql", sql);
    }

    fn rust(&mut self, rust: &str) {
        self.code("rust", rust);
    }

    fn output(&mut self, output: &str) {
        self.paragraph("Observed output from this run:");
        self.code("text", output);
    }

    fn code(&mut self, language: &str, code: &str) {
        self.markdown.push_str("```");
        self.markdown.push_str(language);
        self.markdown.push('\n');
        self.markdown.push_str(code.trim());
        self.markdown.push_str("\n```\n\n");
    }

    fn finish(self) -> String {
        self.markdown.trim_start().to_owned()
    }
}

const DOCKER_RUN_BASH: &str = r#"docker run -d --name diesel-clickhouse-tutorial \
  -p 127.0.0.1::8123 \
  -e CLICKHOUSE_PASSWORD=password \
  --ulimit nofile=262144:262144 \
  clickhouse/clickhouse-server:25.3"#;

const RUN_TUTORIAL_BASH: &str = r#"host_port="$(docker port diesel-clickhouse-tutorial 8123/tcp | sed 's/.*://')"
CLICKHOUSE_URL="http://default:password@127.0.0.1:${host_port}/default" \
  cargo run --example tutorial -- --write docs/TUTORIAL.md"#;

const CONNECT_RUST: &str = r#"use diesel::prelude::*;
use diesel_clickhouse::{ClickHouseConnectionOptions, ClickHouseQueryDsl};

let mut conn = ClickHouseConnectionOptions::new("http://localhost:8123")
    .user("default")
    .password("password")
    .database("default")
    .option("max_threads", "1")
    .connect()?;"#;

const SCHEMA_RUST: &str = r#"diesel::table! {
    use diesel::sql_types::*;
    use diesel_clickhouse::sql_types::*;

    trips (trip_id) {
        trip_id -> UInt32,
        pickup_date -> Date,
        passenger_count -> UInt8,
        tip_amount -> Float,
        total_amount -> Float,
        pickup_ntaname -> Text,
        dropoff_nyct2010_gid -> UInt8,
    }
}"#;

const CREATE_TRIPS_RUST: &str = r#"use diesel_clickhouse::{create_table, merge_tree, to_sql, DataType};

let ddl = create_table("trips")
    .if_not_exists()
    .column("trip_id", DataType::UInt32)
    .column("vendor_id", DataType::enum8([
        ("1", 1), ("2", 2), ("3", 3), ("4", 4),
        ("CMT", 5), ("VTS", 6), ("DDS", 7),
        ("B02512", 10), ("B02598", 11), ("B02617", 12),
        ("B02682", 13), ("B02764", 14), ("", 15),
    ]))
    .column("pickup_date", DataType::Date)
    .column("pickup_datetime", DataType::DateTime)
    // Add the remaining columns in the same shape. See examples/tutorial.rs.
    .column("pickup", DataType::custom("FixedString(25)"))
    .column("dropoff", DataType::custom("FixedString(25)"))
    .engine(
        merge_tree()
            .partition_by(["toYYYYMM(pickup_date)"])
            .order_by(["pickup_datetime"]),
    );

diesel::sql_query(to_sql(&ddl)?).execute(&mut conn)?;"#;

const INSERT_TRIPS_RUST: &str = r#"use diesel::connection::SimpleConnection;

let existing: i64 = trips::table
    .select(diesel::dsl::count_star())
    .first(&mut conn)?;

if existing == 0 {
    conn.batch_execute(INSERT_TRIPS_SQL)?;
}

let row_count: i64 = trips::table
    .select(diesel::dsl::count_star())
    .first(&mut conn)?;"#;

const AVG_TIP_RUST: &str = r#"use diesel::dsl::sql;
use diesel::sql_types::Float;

let avg_tip: f32 = trips::table
    .select(sql::<Float>("round(avg(`tip_amount`), 2)"))
    .first(&mut conn)?;"#;

const BY_PASSENGER_RUST: &str = r#"let by_passenger: Vec<(u8, f32)> = trips::table
    .group_by(trips::passenger_count)
    .select((
        trips::passenger_count,
        sql::<Float>("ceil(avg(`total_amount`), 2)"),
    ))
    .order(trips::passenger_count.asc())
    .load(&mut conn)?;"#;

const DAILY_PICKUPS_RUST: &str = r#"let daily_pickups: Vec<(String, String, i64)> = trips::table
    .group_by((trips::pickup_date, trips::pickup_ntaname))
    .select((
        trips::pickup_date,
        trips::pickup_ntaname,
        diesel::dsl::count_star(),
    ))
    .order((trips::pickup_date.asc(), trips::pickup_ntaname.asc()))
    .limit(10)
    .load(&mut conn)?;"#;

const DICTIONARY_LOOKUP_RUST: &str = r#"use diesel::sql_types::{Bool, Text};

let borough: String = diesel::select(sql::<Text>(
    "dictGet('taxi_zone_dictionary', 'Borough', 132)",
))
.get_result(&mut conn)?;

let has_jfk: bool = diesel::select(sql::<Bool>(
    "dictHas('taxi_zone_dictionary', 132)",
))
.get_result(&mut conn)?;"#;

const BOROUGH_PICKUPS_RUST: &str = r#"fn pickup_borough_expr() -> diesel::expression::SqlLiteral<Text> {
    sql::<Text>(
        "dictGetOrDefault('taxi_zone_dictionary','Borough', \
         toUInt64(`pickup_nyct2010_gid`), 'Unknown')",
    )
}

let borough_pickups: Vec<(i64, String)> = trips::table
    .filter(sql::<Bool>(
        "dropoff_nyct2010_gid = 132 OR dropoff_nyct2010_gid = 138",
    ))
    .group_by(pickup_borough_expr())
    .select((diesel::dsl::count_star(), pickup_borough_expr()))
    .order(diesel::dsl::count_star().desc())
    .load(&mut conn)?;"#;

const JOIN_RUST: &str = r#"#[derive(Debug, diesel::QueryableByName)]
struct BoroughTotal {
    #[diesel(sql_type = diesel::sql_types::BigInt)]
    total: i64,
    #[diesel(sql_type = diesel::sql_types::Text)]
    borough: String,
}

let joined: Vec<BoroughTotal> = diesel::sql_query(JOIN_SQL)
    .load(&mut conn)?;"#;

const INSERT_TRIPS_SQL: &str = r#"
INSERT INTO trips
SELECT * FROM s3(
    'https://datasets-documentation.s3.eu-west-3.amazonaws.com/nyc-taxi/trips_{1..2}.gz',
    'TabSeparatedWithNames', "
    `trip_id` UInt32,
    `vendor_id` Enum8('1' = 1, '2' = 2, '3' = 3, '4' = 4, 'CMT' = 5, 'VTS' = 6, 'DDS' = 7, 'B02512' = 10, 'B02598' = 11, 'B02617' = 12, 'B02682' = 13, 'B02764' = 14, '' = 15),
    `pickup_date` Date,
    `pickup_datetime` DateTime,
    `dropoff_date` Date,
    `dropoff_datetime` DateTime,
    `store_and_fwd_flag` UInt8,
    `rate_code_id` UInt8,
    `pickup_longitude` Float64,
    `pickup_latitude` Float64,
    `dropoff_longitude` Float64,
    `dropoff_latitude` Float64,
    `passenger_count` UInt8,
    `trip_distance` Float64,
    `fare_amount` Float32,
    `extra` Float32,
    `mta_tax` Float32,
    `tip_amount` Float32,
    `tolls_amount` Float32,
    `ehail_fee` Float32,
    `improvement_surcharge` Float32,
    `total_amount` Float32,
    `payment_type` Enum8('UNK' = 0, 'CSH' = 1, 'CRE' = 2, 'NOC' = 3, 'DIS' = 4),
    `trip_type` UInt8,
    `pickup` FixedString(25),
    `dropoff` FixedString(25),
    `cab_type` Enum8('yellow' = 1, 'green' = 2, 'uber' = 3),
    `pickup_nyct2010_gid` Int8,
    `pickup_ctlabel` Float32,
    `pickup_borocode` Int8,
    `pickup_ct2010` String,
    `pickup_boroct2010` String,
    `pickup_cdeligibil` String,
    `pickup_ntacode` FixedString(4),
    `pickup_ntaname` String,
    `pickup_puma` UInt16,
    `dropoff_nyct2010_gid` UInt8,
    `dropoff_ctlabel` Float32,
    `dropoff_borocode` UInt8,
    `dropoff_ct2010` String,
    `dropoff_boroct2010` String,
    `dropoff_cdeligibil` String,
    `dropoff_ntacode` FixedString(4),
    `dropoff_ntaname` String,
    `dropoff_puma` UInt16
") SETTINGS input_format_try_infer_datetimes = 0
"#;

const CREATE_DICTIONARY_SQL: &str = r#"
CREATE DICTIONARY taxi_zone_dictionary
(
  `LocationID` UInt16 DEFAULT 0,
  `Borough` String,
  `Zone` String,
  `service_zone` String
)
PRIMARY KEY LocationID
SOURCE(HTTP(URL 'https://datasets-documentation.s3.eu-west-3.amazonaws.com/nyc-taxi/taxi_zone_lookup.csv' FORMAT 'CSVWithNames'))
LIFETIME(MIN 0 MAX 0)
LAYOUT(HASHED_ARRAY())
"#;

const JOIN_SQL: &str = r#"
SELECT
    count(1) AS total,
    Borough AS borough
FROM trips
JOIN taxi_zone_dictionary
    ON toUInt64(trips.pickup_nyct2010_gid) = taxi_zone_dictionary.LocationID
WHERE dropoff_nyct2010_gid = 132 OR dropoff_nyct2010_gid = 138
GROUP BY borough
ORDER BY total DESC
"#;
